# Generated by Django 5.0.4 on 2024-04-20 19:06

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbtest',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbtests', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_units', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bbtest',
            name='test_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
