# Generated by Django 5.0.4 on 2024-04-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_bbtest_patient_bloodunit_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbtest',
            name='test_date',
            field=models.DateField(),
        ),
    ]
