# Generated by Django 5.0.4 on 2024-04-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_bbtest_test_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbtest',
            old_name='Patient',
            new_name='patient',
        ),
    ]
