# Generated by Django 5.0.4 on 2024-04-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_bbtest_patient_alter_bloodunit_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodunit',
            name='patient',
        ),
        migrations.DeleteModel(
            name='BBTest',
        ),
        migrations.DeleteModel(
            name='BloodUnit',
        ),
    ]
