# Generated by Django 5.0.4 on 2024-04-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_bloodunit_patient_delete_bbtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='antibodyID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='antibodyScreen',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodType',
            field=models.CharField(default='', max_length=3),
        ),
    ]
